[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls-plus", "markdown-oxide"]
soft-wrap.enable = true
# text-width = 80 < this is the default value.
soft-wrap.wrap-at-text-width = true
# formatter = { command = "dprint", args = ["fmt", "--stdin", "md", "--config", "~/.dprint.json"]}
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "never", # <always|never|preserve>
]}

[language-server.ltex-ls-plus.config]
ltex.diagnosticSeverity = "warning"
ltex.ltex-ls.logLevel = "warning"
ltex.disabledRules = { "en-US" = ["PROFANITY"], "en-GB" = ["PROFANITY"] }
ltex.dictionary = { "en-US" = ["builtin"], "en-GB" = ["builtin"] }

[[language]]
name = "latex"
formatter = {command = "prettier", args = [
  "--parser",
  "latex",
  "--prose-wrap",
  "never", # <always|never|preserve?
]}


